services:
  presentation:
    image: presentation
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile

  gcommerce.dbmigrator:
    image: gcommerce.dbmigrator
    build:
      context: .
      dockerfile: src/GCommerce.DbMigrator/Dockerfile

  gcommerce.web:
    image: gcommerce.web
    build:
      context: .
      dockerfile: src/GCommerce.Web/Dockerfile

  gcommerce.web-1:
    image: gcommerce.web-1
    build:
      context: .
      dockerfile: GCommerce.Web/Dockerfile
