<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Brands\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="9.0.3" />
    </ItemGroup>

</Project>
